"use client";
import { useMemo, useState } from "react";
type Candidate = { name: string; source: string; stage: string; version: number };
const stages = ["คัดกรอง", "โทรคุยเบื้องต้น", "สัมภาษณ์", "ข้อเสนอ", "รับเข้าทำงาน"];
export default function DashboardPage() {
  const [jobTitle, setJobTitle] = useState("Tech Lead / Senior Developer"); const [candidateName, setCandidateName] = useState("Narin Chaiyapruk"); const [referrer, setReferrer] = useState("ทีม Engineering");
  const [candidate, setCandidate] = useState<Candidate>({ name: "Narin Chaiyapruk", source: "แนะนำโดยทีม Engineering", stage: stages[0], version: 1 }); const [jobs, setJobs] = useState([jobTitle]); const [editingJob, setEditingJob] = useState<string | null>(null); const [view, setView] = useState<"kanban" | "table">("kanban"); const [filter, setFilter] = useState("ทั้งหมด"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const visible = useMemo(() => filter === "ทั้งหมด" || candidate.stage === filter, [candidate.stage, filter]);
  const saveCandidate = () => { if (!candidateName.trim() || !referrer.trim()) { setMessage("เกิดข้อผิดพลาด: กรุณาระบุชื่อผู้สมัครและผู้แนะนำ"); return; } setLoading(true); setTimeout(() => { setCandidate({ name: candidateName.trim(), source: `แนะนำโดย${referrer.trim()}`, stage: "คัดกรอง", version: candidate.version + 1 }); setLoading(false); setMessage("บันทึกผู้สมัครและสร้างใบสมัครแล้ว"); }, 50); };
  const moveStage = (stage: string) => { if (stage === candidate.stage) return; setCandidate({ ...candidate, stage, version: candidate.version + 1 }); setMessage(`ย้ายผู้สมัครไปขั้นตอน${stage}แล้ว`); };
  return <main style={{ maxWidth: 1180, margin: "0 auto", padding: 40 }}><header style={toolbar}><div><p style={{ color: "#315efb", fontWeight: 700 }}>TALENTFLOW</p><h1>ภาพรวมการสรรหา</h1><p>จัดการตำแหน่งงาน ผู้สมัคร และขั้นตอนการคัดเลือกในที่เดียว</p></div><button onClick={() => document.getElementById("job-form")?.scrollIntoView()} style={primary}>สร้างตำแหน่งงาน</button></header>
    <section style={stats}>{["ตำแหน่งที่เปิด", "ผู้สมัครทั้งหมด", "รอคัดกรอง", "สัมภาษณ์สัปดาห์นี้"].map((label, index) => <article key={label} style={card}><small>{label}</small><h2>{[3, 48, 12, 5][index]}</h2></article>)}</section>
    <section id="job-form" style={card}><h2>ตำแหน่งงาน</h2><ul>{jobs.length ? jobs.map((job) => <li key={job}>{job} <button onClick={() => { setJobTitle(job); setEditingJob(job); }} style={secondary}>แก้ไข</button></li>) : <li>ยังไม่มีตำแหน่งงาน</li>}</ul><label>{editingJob ? "แก้ไขชื่อตำแหน่ง" : "สร้างชื่อตำแหน่ง"}<input value={jobTitle} onChange={(event) => setJobTitle(event.target.value)} /></label><button onClick={() => { setJobs((current) => editingJob ? current.map((job) => job === editingJob ? jobTitle : job) : [...current, jobTitle]); setEditingJob(null); setMessage(`บันทึกตำแหน่ง ${jobTitle}`); }} style={primary}>{editingJob ? "บันทึกการแก้ไข" : "สร้างตำแหน่งงาน"}</button></section>
    <section style={{ ...card, marginTop: 16 }}><div style={toolbar}><div><h2>Applicant Tracker</h2><p>{jobTitle}</p></div><div><button onClick={() => setView("kanban")} style={view === "kanban" ? active : secondary}>คัมบัง</button><button onClick={() => setView("table")} style={view === "table" ? active : secondary}>ตาราง</button><select aria-label="กรองตามขั้นตอน" value={filter} onChange={(event) => setFilter(event.target.value)}><option>ทั้งหมด</option>{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></div></div>{view === "kanban" ? <div style={columns}>{stages.map((stage) => <div key={stage} style={column}><strong>{stage}</strong>{visible && candidate.stage === stage ? <div style={candidateCard}><b>{candidate.name}</b><small>{candidate.source}</small><select aria-label={`ย้าย ${candidate.name}`} value={candidate.stage} onChange={(event) => moveStage(event.target.value)}>{stages.map((item) => <option key={item}>{item}</option>)}</select></div> : <p style={{ color: "#667085" }}>ยังไม่มีผู้สมัคร</p>}</div>)}</div> : <table style={{ width: "100%" }}><thead><tr><th>ชื่อ</th><th>แหล่งที่มา</th><th>ขั้นตอน</th><th>เวอร์ชัน</th></tr></thead><tbody>{visible && <tr><td>{candidate.name}</td><td>{candidate.source}</td><td>{candidate.stage}</td><td>{candidate.version}</td></tr>}</tbody></table>}</section>
    <section style={{ ...card, marginTop: 16 }}><h2>เพิ่มผู้สมัครจากการแนะนำ</h2><div style={formGrid}><label>ชื่อผู้สมัคร<input value={candidateName} onChange={(event) => setCandidateName(event.target.value)} /></label><label>ผู้แนะนำ<input value={referrer} onChange={(event) => setReferrer(event.target.value)} /></label></div><button onClick={saveCandidate} disabled={loading} style={primary}>{loading ? "กำลังบันทึก..." : "สร้างผู้สมัครและใบสมัคร"}</button><button onClick={() => setMessage("ข้อขัดแย้ง: ข้อมูลถูกแก้ไขโดยผู้ใช้อื่น กรุณาโหลดข้อมูลล่าสุดก่อนบันทึก")} style={secondary}>จำลองข้อมูลชนกัน</button><button onClick={() => setMessage("ลองใหม่อีกครั้งได้เลย")} style={secondary}>ลองใหม่</button>{message && <p role="status">{message}</p>}</section></main>;
}
const card = { background: "white", padding: 24, borderRadius: 12, border: "1px solid #e5e7ef" }; const primary = { background: "#315efb", color: "white", border: 0, borderRadius: 8, padding: "11px 16px", cursor: "pointer" }; const secondary = { background: "white", color: "#172033", border: "1px solid #cbd2e1", borderRadius: 8, padding: "10px 14px", cursor: "pointer", marginLeft: 8 }; const active = { ...secondary, background: "#eaf0ff", borderColor: "#315efb" }; const stats = { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, margin: "28px 0" }; const toolbar = { display: "flex", justifyContent: "space-between", alignItems: "center" }; const columns = { display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 12, marginTop: 20 }; const column = { minHeight: 170, background: "#f7f8fb", borderRadius: 8, padding: 12 }; const candidateCard = { background: "white", borderRadius: 8, padding: 12, marginTop: 12, display: "grid", gap: 8, boxShadow: "0 2px 8px #dce2f0" }; const formGrid = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 };
