"use client";

import { useState } from "react";
import { ActionItem, AppShell, Header, Metric, Sidebar } from "../components/talentflow";

export default function DashboardPage() {
  const [message, setMessage] = useState("");
  return <AppShell><Sidebar /><Header /><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 xl:ml-[260px] md:px-6">
    <div><p className="text-xs font-bold uppercase tracking-widest text-[#004cca]">ศูนย์ควบคุมการสรรหา</p><h2 className="mt-2 font-serif text-4xl">วันนี้ต้องจัดการอะไรบ้าง</h2><p className="mt-2 text-[#565e74]">เริ่มจากรายการที่ต้องตัดสินใจก่อน แล้วติดตามภาพรวมของงานสรรหา</p></div>
    <section aria-labelledby="action-heading" className="rounded-xl border border-[#e0e3e5] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h3 id="action-heading" className="text-lg font-semibold">รายการที่ต้องทำ</h3><p className="mt-1 text-sm text-[#565e74]">จัดการรายการเร่งด่วนก่อน เพื่อไม่ให้ผู้สมัครค้างในกระบวนการ</p></div><span className="rounded-full bg-[#ffdad6] px-2 py-1 text-xs font-bold text-[#93000a]">3 รายการ</span></div><div className="mt-4 space-y-3"><ActionItem step="1 · ต้องทำก่อน" title="ตรวจเรซูเม่ที่รอการตัดสินใจ" detail="มี 8 รายการที่ยังค้างอยู่" href="/screening" icon="priority_high" primary /><ActionItem step="2 · วันนี้" title="เตรียมสัมภาษณ์วันนี้" detail="มีนัดหมาย 2 รายการ" href="/interviews" icon="event" /><ActionItem step="3 · ถัดไป" title="คัดกรองผู้สมัครใหม่" detail="มีผู้สมัครใหม่ 3 รายการ" href="/applications" icon="group" /></div></section>
    <div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2"><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-semibold">ภาพรวมการสรรหา</h3><span className="text-sm text-[#565e74]">อัปเดตวันนี้ 09:42</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="ตำแหน่งเปิดอยู่" value="6" href="/jobs" /><Metric label="ผู้สมัครใหม่" value="3" href="/applications" /><Metric label="อยู่ระหว่างสัมภาษณ์" value="8" href="/interviews" /><Metric label="นัดสัปดาห์นี้" value="4" href="/interviews" /></div></section><section className="rounded-xl border border-[#ba1a1a]/20 bg-[#ba1a1a]/5 p-5"><h3 className="flex items-center gap-2 font-semibold text-[#ba1a1a]"><span aria-hidden="true" className="material-symbols-outlined">sync_problem</span>ระบบที่ต้องตรวจสอบ</h3><p className="mt-2 text-sm text-[#424656]">การซิงค์ Payroll ล้มเหลว ระบบยังไม่ส่งข้อมูลซ้ำ</p><button type="button" onClick={() => setMessage("ส่งคำขอเชื่อมต่อใหม่แล้ว")} className="mt-4 rounded-lg border border-[#ba1a1a] px-3 py-2 text-xs font-bold text-[#ba1a1a]">ตรวจสอบการเชื่อมต่อ</button></section></div>{message && <p role="status" className="rounded-lg bg-[#dbe1ff] p-3 text-sm text-[#00174b]">{message}</p>}
  </main></AppShell>;
}
