"use client";

import { useState, useTransition } from "react";
import { createApplication } from "../app/applications/actions";
import { createCandidate } from "../app/discovery/actions";
import type { JobRecord } from "@/application/job-service";
import { AppShell, Header, Sidebar } from "./talentflow";

export function DiscoveryPage({ jobs }: { jobs: JobRecord[] }) {
  const [source, setSource] = useState<"manual" | "referral">("manual");
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  function submit(formData: FormData) { startTransition(async () => { const jobId = String(formData.get("jobId") ?? ""); const candidate = await createCandidate({ fullName: formData.get("fullName"), email: formData.get("email") || undefined, phone: formData.get("phone") || undefined, source, referrerName: source === "referral" ? formData.get("referrerName") : undefined }); if (candidate.error || !candidate.data) { setMessage(candidate.error?.message ?? "เพิ่มผู้สมัครไม่สำเร็จ"); return; } const application = await createApplication(candidate.data.id, jobId); setMessage(application.error ? application.error.message : "เพิ่มผู้สมัครและผูกกับตำแหน่งงานแล้ว"); }); }
  return <AppShell><Sidebar activePath="/discovery" /><Header /><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 xl:ml-[260px] md:px-6"><div><p className="text-xs font-bold uppercase tracking-widest text-[#004cca]">TalentFlow</p><h1 className="mt-2 text-4xl font-serif">เพิ่มผู้สมัคร</h1><p className="mt-1 text-sm text-[#565e74]">เพิ่มผู้สมัครแบบกรอกเองหรือการแนะนำ และผูกกับตำแหน่งงานทันที</p></div><form action={submit} className="max-w-2xl rounded-xl border border-[#e0e3e5] bg-white p-6 shadow-sm"><div className="mb-6 flex border-b border-[#e0e3e5]"><button type="button" onClick={() => setSource("manual")} className={`px-4 py-2 text-sm ${source === "manual" ? "border-b-2 border-[#004cca] font-bold text-[#004cca]" : "text-[#565e74]"}`}>กรอกเอง</button><button type="button" onClick={() => setSource("referral")} className={`px-4 py-2 text-sm ${source === "referral" ? "border-b-2 border-[#004cca] font-bold text-[#004cca]" : "text-[#565e74]"}`}>แนะนำ</button></div><label className="block text-sm font-semibold">ชื่อ-นามสกุล<input name="fullName" required className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label><label className="mt-4 block text-sm font-semibold">อีเมล<input name="email" type="email" className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label><label className="mt-4 block text-sm font-semibold">เบอร์โทรศัพท์<input name="phone" className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label>{source === "referral" && <label className="mt-4 block text-sm font-semibold">ชื่อผู้แนะนำ<input name="referrerName" required className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label>}<label className="mt-4 block text-sm font-semibold">ตำแหน่งงาน<select name="jobId" required className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2"><option value="">เลือกตำแหน่งงาน</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.title}</option>)}</select></label><button type="submit" disabled={pending || jobs.length === 0} className="mt-6 rounded-lg bg-gradient-to-r from-[#0062ff] to-[#38bdf8] px-5 py-2.5 font-semibold text-white disabled:opacity-50">{pending ? "กำลังบันทึก..." : "เพิ่มผู้สมัคร"}</button>{jobs.length === 0 && <p className="mt-3 text-sm text-[#ba1a1a]">ต้องสร้างตำแหน่งงานก่อนเพิ่มผู้สมัคร</p>}{message && <p role="status" className="mt-3 rounded-lg bg-[#dbe1ff] p-3 text-sm">{message}</p>}</form></main></AppShell>;
}
