"use client";

import { FormEvent, useRef, useState } from "react";
import { AppShell, Header, Sidebar } from "./talentflow";

const days = ["จ. 16", "อ. 17", "พ. 18 (วันนี้)", "พฤ. 19", "ศ. 20"];

export function InterviewsView() {
  const [message, setMessage] = useState("");
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const [scheduleStart, setScheduleStart] = useState("11:00");
  const [scheduleEnd, setScheduleEnd] = useState("11:30");
  const [scheduled, setScheduled] = useState(false);
  const [cancelled, setCancelled] = useState(false);
  const [cancelOpen, setCancelOpen] = useState(false);
  const detailsRef = useRef<HTMLElement>(null);
  const timeRef = useRef<HTMLInputElement>(null);
  const focusRescheduleForm = () => { setMessage("เลือกเวลาใหม่เพื่อเลื่อนนัดหมาย"); timeRef.current?.focus(); };
  const showDetails = () => { setMessage("แสดงรายละเอียดนัดหมายที่มีเวลาซ้อนทับกัน"); detailsRef.current?.focus(); };
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage("บันทึกการเลื่อนนัดหมายแล้ว"); };

  return <AppShell><Sidebar activePath="/interviews" /><Header /><main className="min-h-screen bg-[#f8f9fb] md:ml-[260px]"><div className="px-6 py-6">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-serif text-3xl font-bold">ตารางนัดสัมภาษณ์</h1><p className="mt-1 text-sm text-[#565e74]">จัดการตารางนัดหมาย ตรวจสอบเวลาชน และนัดหมายผู้สมัคร</p></div><div className="flex items-center gap-3"><button type="button" onClick={() => setScheduleOpen(true)} className="rounded-lg bg-[#0057d9] px-4 py-2 text-sm font-semibold text-white">นัดหมายสัมภาษณ์</button><div role="group" aria-label="ช่วงเวลาของปฏิทิน" className="flex rounded-lg bg-[#e6e8ec] p-1"><span aria-disabled="true" title="มุมมองวันยังไม่พร้อมใช้งาน" className="px-4 py-2 text-sm">วัน</span><span aria-current="true" className="rounded-md bg-white px-4 py-2 text-sm font-semibold shadow-sm">สัปดาห์</span><span aria-disabled="true" title="มุมมองเดือนยังไม่พร้อมใช้งาน" className="px-4 py-2 text-sm">เดือน</span></div></div></div>
    {scheduleOpen && <section aria-labelledby="schedule-heading" className="mb-6 rounded-xl border border-[#d9dee7] bg-white p-5 shadow-sm"><h2 id="schedule-heading" className="mb-4 text-lg font-semibold">นัดหมายสัมภาษณ์ใหม่</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#565e74]">เวลาเริ่มต้น<input aria-label="เวลาเริ่มต้น" type="time" value={scheduleStart} onChange={(event) => setScheduleStart(event.target.value)} className="mt-1 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2 text-sm" /></label><label className="text-xs font-bold text-[#565e74]">เวลาสิ้นสุด<input aria-label="เวลาสิ้นสุด" type="time" value={scheduleEnd} onChange={(event) => setScheduleEnd(event.target.value)} className="mt-1 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2 text-sm" /></label></div>{scheduled ? <button type="button" onClick={() => setMessage("เลื่อนนัดหมายแล้ว")} className="mt-4 rounded-lg bg-[#071d37] px-4 py-2 text-sm font-semibold text-white">บันทึกการเลื่อนนัดหมาย</button> : <button type="button" onClick={() => { if (scheduleStart === "11:00") { setMessage("INTERVIEW_CONFLICT: เวลาสัมภาษณ์ซ้อนทับกับ Team Sync"); return; } setScheduled(true); setMessage("สร้างนัดหมายแล้ว"); }} className="mt-4 rounded-lg bg-[#071d37] px-4 py-2 text-sm font-semibold text-white">ตรวจสอบและสร้างนัดหมาย</button>}</section>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,1fr)]"><section aria-label="ปฏิทินสัมภาษณ์ประจำสัปดาห์" className="flex min-h-[600px] flex-col overflow-hidden rounded-xl border border-[#d9dee7] bg-white"><div className="grid grid-cols-5 border-b border-[#e1e4ea] py-3 text-center text-sm font-medium text-[#565e74]">{days.map((day, index) => <div key={day} className={index === 2 ? "text-[#0057d9]" : ""}>{day}</div>)}</div><div className="relative grid min-h-[520px] flex-1 grid-cols-5"><div className="absolute bottom-0 left-0 top-0 z-10 flex w-12 flex-col border-r border-[#e1e4ea] bg-white/70 py-2 pr-2 text-right text-xs text-[#7c8292]"><span className="h-16">09:00</span><span className="h-16">10:00</span><span className="h-16">11:00</span><span className="h-16">12:00</span><span className="h-16">13:00</span><span className="h-16">14:00</span></div>{days.map((day, index) => <div key={day} className={`relative border-r border-[#e1e4ea] ${index === 2 ? "bg-[#dbe3ff]/20" : ""}`}>
      {index === 1 && <div className="absolute left-2 right-2 top-8 h-[60px] rounded border-l-4 border-[#087b99] bg-[#d4f1f0] p-2"><b className="block text-sm">UX Researcher</b><span className="text-xs text-[#565e74]">สมหญิง ใจดี</span></div>}
      {index === 2 && <><div aria-hidden="true" className="absolute left-0 right-0 top-20 z-20 h-px bg-[#ba1a1a]" /><article className="absolute left-2 right-2 top-32 h-[60px] rounded border-l-4 border-[#ba1a1a] bg-[#ffdad6] p-2"><div className="flex justify-between text-sm font-medium">Senior Developer<span aria-hidden="true" className="material-symbols-outlined text-[16px]">warning</span></div><span className="text-xs text-[#565e74]">กฤษณะ แสงอรุณ</span></article><article className="absolute left-6 right-2 top-36 z-10 h-[60px] rounded border-l-4 border-[#0057d9] bg-[#dbe3ff] p-2 opacity-90"><b className="block text-sm">Team Sync</b><span className="text-xs text-[#565e74]">Internal</span><button type="button" onClick={focusRescheduleForm} className="mt-1 text-xs font-semibold text-[#0057d9]">เลื่อนนัดหมาย</button></article></>}
      {index === 4 && <article className="absolute left-2 right-2 top-48 h-[120px] rounded border-l-4 border-[#0057d9] bg-[#dbe3ff] p-2"><b className="block text-sm">Product Manager - Final</b><span className="text-xs text-[#565e74]">วิชัย รักษา</span><span className="mt-2 block text-xs text-[#565e74]"><span aria-hidden="true" className="material-symbols-outlined mr-1 align-middle text-[14px]">videocam</span>Google Meet</span>{cancelled ? <span className="mt-1 block text-xs font-semibold text-[#ba1a1a]">ยกเลิกแล้ว</span> : <button type="button" onClick={() => setCancelOpen(true)} className="mt-1 text-xs font-semibold text-[#ba1a1a]">ยกเลิก</button>}{cancelOpen && !cancelled && <div className="mt-2"><label className="sr-only" htmlFor="cancel-reason">เหตุผลการยกเลิก</label><input id="cancel-reason" aria-label="เหตุผลการยกเลิก" className="w-full rounded border px-1 text-xs" placeholder="เหตุผลการยกเลิก" /><button type="button" onClick={() => { setCancelled(true); setCancelOpen(false); setMessage("ยกเลิกนัดหมายแล้ว"); }} className="mt-1 text-xs font-semibold text-[#ba1a1a]">ยืนยันการยกเลิก</button></div>}</article>}
    </div>)}</div></section>
    <div className="flex flex-col gap-6"><section aria-labelledby="conflict-heading" className="rounded-xl border border-[#ba1a1a]/30 bg-[#ffdad6]/30 p-5"><div className="flex items-start gap-3"><span aria-hidden="true" className="material-symbols-outlined rounded-full bg-[#ba1a1a]/10 p-2 text-[#ba1a1a]">warning</span><div><h2 id="conflict-heading" className="font-semibold">พบตารางซ้อนทับกัน</h2><p className="mt-1 text-sm text-[#565e74]">สัมภาษณ์ Senior Developer ชนกับ Team Sync เวลา 11:00 น. วันนี้</p><div className="mt-4 flex gap-2"><button type="button" onClick={focusRescheduleForm} className="rounded-md bg-[#ba1a1a] px-3 py-1.5 text-sm font-semibold text-white">เลื่อนเวลา</button><button type="button" onClick={showDetails} className="rounded-md border border-[#c2c6d9] bg-white px-3 py-1.5 text-sm">ดูรายละเอียด</button></div></div></div></section>
      <section ref={detailsRef} tabIndex={-1} aria-labelledby="appointment-details-heading" className="rounded-xl border border-[#d9dee7] bg-white p-6 shadow-sm"><h2 id="appointment-details-heading" className="mb-4 text-lg font-semibold">รายละเอียดนัดหมาย</h2><form onSubmit={handleSubmit} onReset={() => setMessage("ยกเลิกการเปลี่ยนแปลงแล้ว")}>
        <label className="mb-4 block text-xs font-bold uppercase text-[#565e74]">ผู้สมัคร<select name="candidate" className="mt-1 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2 text-sm"><option>กฤษณะ แสงอรุณ (Senior Dev)</option><option>สมหญิง ใจดี (UX Researcher)</option></select></label>
        <div className="grid grid-cols-2 gap-4"><label className="text-xs font-bold uppercase text-[#565e74]">วันที่<input name="date" type="date" defaultValue="2023-10-18" className="mt-1 w-full rounded-lg border border-[#c2c6d9] px-3 py-2 text-sm" /></label><label className="text-xs font-bold uppercase text-[#565e74]">เวลา<input ref={timeRef} name="time" type="time" defaultValue="11:00" aria-describedby="schedule-conflict-description" className="mt-1 w-full rounded-lg border border-[#ba1a1a] bg-[#ffdad6]/20 px-3 py-2 text-sm" /></label></div><p id="schedule-conflict-description" className="sr-only">เวลานี้ซ้อนทับกับ Team Sync</p>
        <label className="mt-4 block text-xs font-bold uppercase text-[#565e74]">ผู้สัมภาษณ์<input name="interviewer" value="อานนท์ ภักดี (Tech Lead)" readOnly className="mt-1 w-full rounded-lg border border-[#c2c6d9] px-3 py-2 text-sm" /></label>
        <fieldset className="mt-4"><legend className="sr-only">รูปแบบการสัมภาษณ์</legend><div className="flex gap-5 text-sm"><label className="flex items-center gap-1"><input type="radio" defaultChecked name="format" value="online" /> Online (Meet)</label><label className="flex items-center gap-1"><input type="radio" name="format" value="onsite" /> On-site</label></div></fieldset>
        <hr className="my-5 border-[#e1e4ea]" /><label className="block text-xs font-bold uppercase text-[#565e74]">เหตุผลการเปลี่ยนแปลง (ถ้ามี)<textarea name="reason" className="mt-1 h-20 w-full resize-none rounded-lg border border-[#c2c6d9] p-3 text-sm" placeholder="ระบุเหตุผล..." /></label><div className="mt-3 flex gap-3"><button type="submit" className="flex-1 rounded-lg bg-[#071d37] py-2.5 text-sm font-semibold text-white">เลื่อนนัดหมาย</button><button type="reset" className="rounded-lg border border-[#ba1a1a] px-4 py-2.5 text-sm text-[#ba1a1a]">ยกเลิก</button></div>
      </form>{message && <p role="status" aria-live="polite" className="mt-3 rounded-lg bg-[#dbe3ff] p-3 text-sm">{message}</p>}</section>
    </div></div>
  </div></main></AppShell>;
}
