"use client";

import { useState, useTransition } from "react";
import { createDraftJob } from "../app/jobs/actions";
import type { JobRecord } from "@/application/job-service";
import { AppShell, Header, Sidebar } from "./talentflow";

export function JobsPage({ initialJobs }: { initialJobs: JobRecord[] }) {
  const [jobs, setJobs] = useState(initialJobs);
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  function submit(formData: FormData) { startTransition(async () => { const result = await createDraftJob({ title: formData.get("title"), description: formData.get("description"), department: formData.get("department") || undefined }); if (result.error || !result.data) { setMessage(result.error?.message ?? "บันทึกไม่สำเร็จ"); return; } setJobs((current) => [result.data as JobRecord, ...current]); setMessage("บันทึกตำแหน่งงานเป็นฉบับร่างแล้ว"); }); }
  return <AppShell><Sidebar activePath="/jobs" /><Header /><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 xl:ml-[260px] md:px-6"><div><p className="text-xs font-bold uppercase tracking-widest text-[#004cca]">TalentFlow</p><h1 className="mt-2 text-4xl font-serif">ตำแหน่งงาน</h1><p className="mt-1 text-sm text-[#565e74]">สร้างและจัดการประกาศรับสมัครงาน</p></div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-xl border border-[#e0e3e5] bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">รายการตำแหน่งงาน</h2><div className="mt-4 space-y-3">{jobs.map((job) => <article key={job.id} className="rounded-lg border border-[#e0e3e5] p-4"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{job.title}</h3><p className="mt-1 text-sm text-[#565e74]">{job.department ?? "ไม่ระบุแผนก"}</p></div><span className="rounded-full bg-[#dbe1ff] px-2 py-1 text-xs font-bold text-[#004cca]">{job.status === "draft" ? "ฉบับร่าง" : job.status}</span></div><p className="mt-3 border-t border-[#e0e3e5] pt-3 text-sm text-[#565e74]">{job.description}</p></article>)}{jobs.length === 0 && <p className="text-sm text-[#565e74]">ยังไม่มีตำแหน่งงาน</p>}</div></section><form action={submit} className="rounded-xl border border-[#e0e3e5] bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">สร้างตำแหน่งงาน</h2><label className="mt-4 block text-sm font-semibold">ชื่อตำแหน่ง<input name="title" required placeholder="เช่น Senior Developer" className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label><label className="mt-3 block text-sm font-semibold">แผนก<input name="department" placeholder="เช่น Engineering" className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label><label className="mt-3 block text-sm font-semibold">รายละเอียดงาน<textarea name="description" required placeholder="รายละเอียดงาน" rows={5} className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" /></label><button type="submit" disabled={pending} className="mt-4 w-full rounded-lg bg-gradient-to-r from-[#0062ff] to-[#38bdf8] px-4 py-2 font-semibold text-white disabled:opacity-50">{pending ? "กำลังบันทึก..." : "บันทึกฉบับร่าง"}</button>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</form></div></main></AppShell>;
}
