"use client";
import { useMemo, useState } from "react";
import { runScreening, uploadResume } from "../app/screening/actions";
import { AppShell, Header, Sidebar } from "./talentflow";
export type ScreeningTarget={applicationId:string;candidateId:string;candidateName:string;jobId:string;jobTitle:string;jobDescription:string;resumeId:string|null;resumeFileName:string|null};
export type ScreeningHistory={id:string;applicationId:string;resumeId:string;status:string;score:number|null;summary:string;evidence:string[];risks:string[];createdAt:string};
export type ScreeningWorkspaceData={targets:ScreeningTarget[];history:ScreeningHistory[];loadError:string|null};
type Result={score:number;summary:string;scores:{skills:number;experience:number;cultureCommunication:number};reasoning:{skills:string;experience:string;cultureCommunication:string};strengths:string[];prescreenQuestions:string[];teamInterviewReport:{summary:string;focusAreas:string[];recommendation:string}};
export function ScreeningWorkspace({data}:{data:ScreeningWorkspaceData}){const[id,setId]=useState(data.targets[0]?.applicationId??"");const[file,setFile]=useState<File|null>(null);const[rid,setRid]=useState(data.targets[0]?.resumeId??"");const[text,setText]=useState("");const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const target=useMemo(()=>data.targets.find(x=>x.applicationId===id),[data.targets,id]);
const start=async()=>{if(!target)return;setBusy(true);setError("");try{let resumeId=rid;if(file){const r=await uploadResume(target.candidateId,file);if("error"in r){setError(r.error.message);return}resumeId=r.data.id;setRid(resumeId)}if(!text.trim()){setError("ระบบจัดเก็บไฟล์แล้ว แต่ยังต้องใช้ข้อความเรซูเม่เพื่อวิเคราะห์");return}const r=await runScreening({applicationId:target.applicationId,resumeId,jobDescription:target.jobDescription,resumeText:text});if("error"in r){setError(r.error.message);return}setResult(r.data.result)}catch{setError("ไม่สามารถวิเคราะห์เรซูเม่ได้ กรุณาลองใหม่")}finally{setBusy(false)}};
return <AppShell><Sidebar activePath="/screening"/><Header activePath="/screening"/><main className="p-8 md:ml-[260px]"><h1 className="font-serif text-4xl">คัดกรองเรซูเม่</h1>{data.loadError&&<p role="alert">{data.loadError}</p>}{target&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><section><select aria-label="ผู้สมัครและตำแหน่งงาน" value={id} onChange={e=>{const t=data.targets.find(x=>x.applicationId===e.target.value);setId(e.target.value);setRid(t?.resumeId??"");setResult(null)}}>{data.targets.map(x=><option key={x.applicationId} value={x.applicationId}>{x.candidateName} — {x.jobTitle}</option>)}</select><input aria-label="screening-resume-file" className="mt-5" type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/><textarea aria-label="ข้อความเรซูเม่" className="mt-5 w-full border p-3" rows={8} value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy||(!rid&&!file)} onClick={start}>{busy?"กำลังวิเคราะห์...":"เริ่มการวิเคราะห์ AI"}</button>{error&&<p role="alert">{error}</p>}</section><section>{!result?<div>ผลลัพธ์จะแสดงที่นี่หลังจากวิเคราะห์และบันทึกสำเร็จ</div>:<><div><p>คะแนนรวม</p><strong>{result.score}/10</strong>{([['ทักษะ','skills'],['ประสบการณ์','experience'],['วัฒนธรรมและการสื่อสาร','cultureCommunication']] as const).map(([label,key])=><div key={key}><p>{label}</p><strong>{result.scores[key]}/10</strong><p>{result.reasoning[key]}</p></div>)}<p>{result.summary}</p></div><div><h2>จุดแข็ง</h2><ul>{result.strengths.map(x=><li key={x}>{x}</li>)}</ul><h2>คำถามคัดกรองเบื้องต้น</h2><ul>{result.prescreenQuestions.map(x=><li key={x}>{x}</li>)}</ul><h2>รายงานสำหรับทีมสัมภาษณ์</h2><p>{result.teamInterviewReport.summary}</p><ul>{result.teamInterviewReport.focusAreas.map(x=><li key={x}>{x}</li>)}</ul><p>{result.teamInterviewReport.recommendation}</p></div></>}</section></div>}</main></AppShell>}
