"use client";

import type { ReactNode } from "react";
import { logoutAction } from "../app/auth/actions";

const navItems = [
  ["dashboard", "แดชบอร์ด", "/"],
  ["work", "ตำแหน่งงาน", "/jobs"],
  ["person_search", "ค้นหาผู้สมัคร", "/discovery"],
  ["description", "คัดกรองเรซูเม่", "/screening"],
  ["group", "ระบบติดตามผู้สมัคร", "/applications"],
  ["calendar_today", "ตารางนัดสัมภาษณ์", "/interviews"],
] as const;

export function AppShell({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-[#f7f9fb] text-[#191c1e]">{children}</div>; }

export function Sidebar({ activePath = "/" }: { activePath?: string }) { return <aside className="fixed inset-y-0 left-0 z-50 hidden w-[260px] flex-col border-r border-white/10 bg-[#020617] px-4 py-6 shadow-xl md:flex"><div className="mb-8 flex items-center gap-3 px-2"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-r from-[#0062ff] to-[#38bdf8] text-white"><span aria-hidden="true" className="material-symbols-outlined">bolt</span></div><div><h1 className="font-serif text-2xl font-bold text-white">TalentFlow</h1><p className="text-sm text-[#bec6e0]">Executive Precision</p></div></div><nav className="flex-1 space-y-2">{navItems.map(([icon, label, href]) => <a key={label} href={href} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-sm transition ${href === activePath ? "bg-[#0062ff] text-white" : "text-[#bec6e0] hover:bg-white/5 hover:text-white"}`}><span aria-hidden="true" className="material-symbols-outlined">{icon}</span>{label}</a>)}</nav><div className="space-y-2 border-t border-white/10 pt-6"><a href="/settings" className="flex items-center gap-3 rounded-lg px-4 py-3 text-sm text-[#bec6e0] hover:bg-white/5 hover:text-white"><span aria-hidden="true" className="material-symbols-outlined">settings</span>ตั้งค่า</a><form action={logoutAction}><button type="submit" className="flex w-full items-center gap-3 rounded-lg px-4 py-3 text-sm text-[#bec6e0] hover:bg-white/5 hover:text-white"><span aria-hidden="true" className="material-symbols-outlined">logout</span>ออกจากระบบ</button></form></div></aside>; }

export function Header({ showSearch = false, searchValue = "", onSearch }: { onCreateJob?: () => void; showSearch?: boolean; searchValue?: string; onSearch?: (value: string) => void } = {}) { return <header className="sticky top-0 z-40 flex h-16 items-center justify-between gap-4 border-b border-[#e0e3e5] bg-white px-6 md:ml-[260px]"><div className={showSearch ? "relative block w-full max-w-md" : "hidden"}><span aria-hidden="true" className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-xl text-[#7c8292]">search</span><label htmlFor="global-search" className="sr-only">ค้นหาผู้สมัครหรือตำแหน่ง</label><input id="global-search" type="search" value={searchValue} onChange={(event) => onSearch?.(event.target.value)} className="w-full rounded-full border border-[#bec5d8] bg-[#fbfcff] py-2 pl-10 pr-4 text-sm" placeholder="ค้นหาผู้สมัคร, ตำแหน่ง..." /></div><div className="flex items-center justify-end gap-4"><button type="button" disabled aria-label="การแจ้งเตือนยังไม่พร้อมใช้งาน" title="การแจ้งเตือนยังไม่พร้อมใช้งานในรุ่นนี้" className="rounded-full p-2 text-[#565e74]"><span aria-hidden="true" className="material-symbols-outlined">notifications</span></button><a href="/help" aria-label="เปิดศูนย์ช่วยเหลือ" className="rounded-full p-2 text-[#565e74] hover:bg-[#f2f4f6]"><span aria-hidden="true" className="material-symbols-outlined">help_outline</span></a><a href="/jobs" className="rounded-lg bg-gradient-to-r from-[#0062ff] to-[#38bdf8] px-4 py-2 text-sm font-bold text-white shadow-sm hover:-translate-y-0.5">สร้างตำแหน่งงาน</a><div role="img" aria-label="ผู้ใช้ปัจจุบัน" className="h-8 w-8 rounded-full border border-[#c2c6d9] bg-[#dae2fd]" /></div></header>; }

export function ActionItem({ step, title, detail, href, icon, primary = false }: { step: string; title: string; detail: string; href: string; icon: string; primary?: boolean }) { return <a href={href} className={`group flex items-center justify-between gap-4 rounded-lg border p-4 transition-colors ${primary ? "border-2 border-[#004cca] bg-[#dbe1ff]/50 hover:bg-[#dbe1ff]" : "border-[#e0e3e5] bg-white hover:border-[#004cca] hover:bg-[#dbe1ff]/30"}`}><span className="flex items-center gap-3"><span aria-hidden="true" className={`material-symbols-outlined rounded-lg p-2 ${primary ? "bg-[#004cca] text-white" : "bg-[#dae2fd] text-[#004cca]"}`}>{icon}</span><span><span className="block text-xs font-bold uppercase tracking-wide text-[#004cca]">{step}</span><strong className="mt-1 block text-sm">{title}</strong><span className="block text-sm text-[#565e74]">{detail}</span></span></span><span aria-hidden="true" className="material-symbols-outlined text-[#004cca] transition-transform group-hover:translate-x-1">arrow_forward</span></a>; }

export function Metric({ label, value, href }: { label: string; value: string; href: string }) { return <a href={href} className="rounded-xl border border-[#e0e3e5] bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="text-sm text-[#565e74]">{label}</span><strong className="mt-2 block font-serif text-3xl">{value}</strong></a>; }
