"use client";

import { useState } from "react";
import type { ReactNode } from "react";
import { AppShell, Header, Sidebar } from "./talentflow";

const jobs = ["Senior Frontend Engineer", "Product Designer", "Tech Lead / Senior Developer"];
const panel = "rounded-xl border border-[#e0e3e5] bg-white p-6 shadow-[0_2px_8px_rgba(15,23,42,.06)]";
const primary = "rounded-lg bg-gradient-to-r from-[#0062ff] to-[#38bdf8] px-4 py-2 text-sm font-bold text-white shadow-sm hover:-translate-y-0.5";
const secondary = "rounded-lg border border-[#c2c6d9] bg-white px-4 py-2 text-sm font-semibold text-[#004cca] hover:bg-[#dbe1ff]/40";

function PageFrame({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <AppShell><Sidebar /><Header /><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 xl:ml-[260px] md:px-6"><div><p className="text-xs font-bold uppercase tracking-widest text-[#004cca]">TalentFlow</p><h2 className="mt-2 font-serif text-4xl">{title}</h2><p className="mt-2 text-[#565e74]">{description}</p></div>{children}</main></AppShell>;
}

function JobSelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold">ตำแหน่งงาน<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 block w-full rounded-lg border border-[#c2c6d9] bg-white px-3 py-2"><option value="">เลือกตำแหน่งงาน</option>{jobs.map((job) => <option key={job}>{job}</option>)}</select></label>; }

function JobsView() { const [message, setMessage] = useState(""); return <PageFrame title="ตำแหน่งงาน" description="สร้างและจัดการประกาศรับสมัครงาน"><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className={panel}><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-semibold">รายการตำแหน่งงาน</h3><div className="flex gap-2"><button className={secondary}>ทั้งหมด 24</button><button className={secondary}>เปิดรับ 12</button></div></div><div className="space-y-3">{[["Senior React Developer", "เปิดรับ", "ผู้สมัครใหม่ 12"], ["UX/UI Designer", "ฉบับร่าง", "แก้ไขล่าสุด 2 ชั่วโมงที่แล้ว"], ["Data Analyst", "ปิดรับ", "ผู้สมัครทั้งหมด 84"]].map(([name, status, detail]) => <article key={name} className="rounded-lg border border-[#e0e3e5] p-4 hover:border-[#004cca]"><div className="flex items-start justify-between"><div><h4 className="font-semibold">{name}</h4><p className="mt-1 text-sm text-[#565e74]">Engineering Department · กรุงเทพมหานคร</p></div><span className="rounded-full bg-[#dbe1ff] px-2 py-1 text-xs font-bold text-[#004cca]">{status}</span></div><div className="mt-4 border-t border-[#e0e3e5] pt-3 text-sm text-[#565e74]">{detail}</div></article>)}</div></section><section className={panel}><h3 className="text-lg font-semibold">สร้างตำแหน่งงาน</h3><p className="mt-1 text-sm text-[#565e74]">บันทึกเป็นฉบับร่างก่อนเปิดรับสมัครได้</p><label className="mt-5 block text-sm font-semibold">ชื่อตำแหน่ง<input className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" placeholder="เช่น Senior Developer" /></label><label className="mt-4 block text-sm font-semibold">แผนก<select className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2"><option>เลือกแผนก</option><option>Engineering</option><option>Product</option></select></label><label className="mt-4 block text-sm font-semibold">รายละเอียดงาน<textarea className="mt-2 block w-full rounded-lg border border-[#c2c6d9] px-3 py-2" rows={4} /></label><button onClick={() => setMessage("บันทึกตำแหน่งงานเป็นฉบับร่างแล้ว")} className={`${primary} mt-5 w-full`}>บันทึกฉบับร่าง</button>{message && <p role="status" className="mt-3 rounded-lg bg-[#dbe1ff] p-3 text-sm">{message}</p>}</section></div></PageFrame>; }

function DiscoveryView() { const [job, setJob] = useState(""); const [message, setMessage] = useState(""); return <PageFrame title="ค้นหาผู้สมัคร" description="เลือกตำแหน่งงานก่อนเริ่มค้นหาและตรวจหลักฐาน"><section className={`${panel} space-y-5`}><div className="flex flex-wrap items-end justify-between gap-4"><div className="w-full max-w-xl"><JobSelect value={job} onChange={setJob} /></div><button disabled={!job} onClick={() => setMessage("ค้นหาผู้สมัครสำเร็จ กรุณาตรวจหลักฐานก่อนอนุมัติ")} className={`${primary} disabled:cursor-not-allowed disabled:opacity-50`}>เริ่มค้นหา</button></div>{job && <article className="overflow-hidden rounded-xl border border-[#e0e3e5]"><header className="flex items-center justify-between bg-[#f2f4f6] p-5"><div><h3 className="text-lg font-bold">กิตติพงษ์ วิริยะ</h3><p className="text-sm text-[#565e74]">Senior Frontend Developer · TechCorp</p></div><div className="text-center"><strong className="block text-3xl text-[#004cca]">94</strong><span className="text-xs text-[#565e74]">คะแนนความเหมาะสม</span></div></header><div className="grid gap-5 p-5 md:grid-cols-3"><div><h4 className="font-semibold">หลักฐานที่พบ</h4><ul className="mt-3 space-y-2 text-sm text-[#424656]"><li>✓ React และ TypeScript 5 ปี</li><li>✓ ผ่าน Technical Test 95%</li><li>✓ เคยออกแบบระบบระดับองค์กร</li></ul></div><div><h4 className="font-semibold text-[#ba1a1a]">ข้อควรตรวจสอบ</h4><p className="mt-3 text-sm text-[#424656]">ประสบการณ์จัดการทีมขนาดใหญ่ยังจำกัด และคาดหวังเงินเดือนสูงกว่าโครงสร้าง 10%</p></div><div className="flex flex-col justify-center gap-3"><button onClick={() => setMessage("อนุมัติแล้วและส่งต่อไปขั้นตอนสัมภาษณ์")} className={primary}>อนุมัติเพื่อสัมภาษณ์</button><button onClick={() => setMessage("พักผลลัพธ์ไว้ให้ HR ตรวจสอบ")} className={secondary}>รอการตรวจสอบ</button><button onClick={() => setMessage("กรุณาระบุเหตุผลก่อนปฏิเสธ")} className="rounded-lg border border-[#ba1a1a] px-4 py-2 text-sm font-semibold text-[#ba1a1a]">ปฏิเสธ</button></div></div></article>}{message && <p role="status" className="rounded-lg bg-[#dbe1ff] p-3 text-sm">{message}</p>}</section></PageFrame>; }

function ScreeningView() { const [job, setJob] = useState(""); const [message, setMessage] = useState(""); return <PageFrame title="คัดกรองเรซูเม่" description="วิเคราะห์เรซูเม่โดยมี HR ตรวจสอบก่อนตัดสินใจ"><div className="grid gap-6 lg:grid-cols-2"><section className={panel}><h3 className="text-lg font-semibold">เริ่มการวิเคราะห์</h3><div className="mt-5"><JobSelect value={job} onChange={setJob} /></div><div className="mt-5 rounded-xl border-2 border-dashed border-[#c2c6d9] bg-[#f2f4f6] p-10 text-center"><span className="material-symbols-outlined text-4xl text-[#004cca]">upload_file</span><p className="mt-2 font-semibold">อัปโหลดเรซูเม่</p><p className="mt-1 text-sm text-[#565e74]">รองรับ PDF และ DOCX</p></div><button disabled={!job} onClick={() => setMessage("วิเคราะห์เสร็จแล้ว ผลลัพธ์พร้อมให้ HR ตรวจสอบ")} className={`${primary} mt-5 w-full disabled:opacity-50`}>เริ่มการวิเคราะห์</button></section><section className={panel}><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">ผลการประเมิน</h3><span className="rounded-full bg-[#ffdad6] px-2 py-1 text-xs font-bold text-[#93000a]">รอ HR ตรวจสอบ</span></div><div className="mt-5 rounded-lg bg-[#dbe1ff]/50 p-5"><strong className="text-3xl text-[#004cca]">86</strong><p className="mt-1 text-sm">คะแนนความเหมาะสม</p></div><ul className="mt-5 space-y-3 text-sm"><li>✓ ทักษะตรงกับตำแหน่ง 8 จาก 10 รายการ</li><li>✓ ประสบการณ์ตรง 4 ปี</li><li>! ต้องตรวจสอบช่วงว่างงาน 6 เดือน</li></ul>{message && <p role="status" className="mt-5 rounded-lg bg-[#dbe1ff] p-3 text-sm">{message}</p>}</section></div></PageFrame>; }

function ApplicationsView() { const [stage, setStage] = useState("คัดกรอง"); return <PageFrame title="ติดตามผู้สมัคร" description="เปลี่ยนขั้นตอนและบันทึกการตัดสินใจของ HR"><section className={panel}><div className="flex flex-wrap items-end justify-between gap-4"><JobSelect value="Tech Lead / Senior Developer" onChange={() => undefined} /><div className="flex gap-2"><button className={secondary}>บอร์ด</button><button className={secondary}>รายการ</button></div></div><div className="mt-6 grid gap-4 md:grid-cols-5">{["คัดกรอง", "โทรคุยเบื้องต้น", "สัมภาษณ์", "ข้อเสนอ", "รับเข้าทำงาน"].map((item) => <div key={item} className="min-h-44 rounded-lg bg-[#f2f4f6] p-3"><strong className="text-sm">{item}</strong>{item === stage && <div className="mt-3 rounded-lg bg-white p-3 shadow-sm"><b>Narin Chaiyapruk</b><p className="mt-1 text-xs text-[#565e74]">แนะนำโดยทีม Engineering</p><select aria-label="เปลี่ยนขั้นตอนผู้สมัคร" value={stage} onChange={(event) => setStage(event.target.value)} className="mt-3 w-full rounded border border-[#c2c6d9] px-2 py-1 text-xs">{["คัดกรอง", "โทรคุยเบื้องต้น", "สัมภาษณ์", "ข้อเสนอ", "รับเข้าทำงาน"].map((s) => <option key={s}>{s}</option>)}</select></div>}</div>)}</div></section></PageFrame>; }

function InterviewsView() { const [message, setMessage] = useState(""); return <PageFrame title="ตารางนัดสัมภาษณ์" description="สร้างนัดหมายโดยตรวจสอบเวลาชนก่อนเสมอ"><section className={panel}><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">สัปดาห์นี้</h3><p className="mt-1 text-sm text-[#565e74]">4 นัดหมาย · 1 รายการต้องติดตาม</p></div><button onClick={() => setMessage("เลือกผู้สมัครและเวลาที่ต้องการนัดหมาย")} className={primary}>นัดหมายใหม่</button></div><div className="mt-6 space-y-3"><article className="flex items-center justify-between rounded-lg border border-[#e0e3e5] p-4"><div><b>วันนี้ · 10:00–10:30</b><p className="mt-1 text-sm text-[#565e74]">Narin Chaiyapruk · Tech Lead</p></div><button onClick={() => setMessage("เวลานี้ไม่ว่าง กรุณาเลือกเวลาใหม่")} className="rounded-lg border border-[#ba1a1a] px-3 py-2 text-sm font-semibold text-[#ba1a1a]">เลื่อนเวลา</button></article></div>{message && <p role="status" className="mt-4 rounded-lg bg-[#ffdad6] p-3 text-sm text-[#93000a]">{message}</p>}</section></PageFrame>; }

function SettingsView() { const [saved, setSaved] = useState(false); return <PageFrame title="ตั้งค่าพื้นที่ทำงาน" description="จัดการการแจ้งเตือน สิทธิ์ และการเชื่อมต่อ"><div className="grid gap-6 md:grid-cols-2"><section className={panel}><h3 className="text-lg font-semibold">การแจ้งเตือน</h3><p className="mt-1 text-sm text-[#565e74]">เลือกเหตุการณ์ที่ต้องการให้ HR รับการแจ้งเตือน</p><label className="mt-5 flex gap-3 text-sm"><input type="checkbox" defaultChecked /> มีเรซูเม่รอตรวจสอบ</label><label className="mt-3 flex gap-3 text-sm"><input type="checkbox" defaultChecked /> เวลาสัมภาษณ์ชนกัน</label></section><section className={panel}><h3 className="text-lg font-semibold">สิทธิ์และการเชื่อมต่อ</h3><p className="mt-1 text-sm text-[#565e74]">การเปลี่ยนแปลงสำคัญต้องมีเหตุผลและ audit log</p><button onClick={() => setSaved(true)} className={`${primary} mt-5`}>บันทึกการตั้งค่า</button>{saved && <p role="status" className="mt-3 text-sm text-[#166534]">บันทึกการตั้งค่าแล้ว</p>}</section></div></PageFrame>; }

function HelpView() { return <PageFrame title="ศูนย์ช่วยเหลือ" description="คำแนะนำและแนวทางแก้ไขปัญหาตาม workflow"><div className="space-y-4">{[["เริ่มต้นใช้งานอย่างไร", "เริ่มจาก Dashboard แล้วเลือกงานที่ต้องทำ จากนั้นทำงานตาม context ของแต่ละหน้า"], ["ถ้า AI ล้มเหลวทำอย่างไร", "ตรวจสอบ error code แล้วกดลองใหม่ ระบบต้องใช้ idempotency key เดิมและไม่สร้างข้อมูลซ้ำ"], ["ถ้าเวลาสัมภาษณ์ชนกันทำอย่างไร", "ระบบจะไม่สร้างนัดหมาย ให้เลือกเวลาใหม่หรือเลื่อนไปวันอื่น"]].map(([title, detail]) => <details key={title} open className={panel}><summary className="cursor-pointer font-semibold">{title}</summary><p className="mt-3 text-sm text-[#565e74]">{detail}</p></details>)}</div></PageFrame>; }

export function WorkspacePage({ page }: { page: "jobs" | "discovery" | "screening" | "applications" | "interviews" | "settings" | "help" }) { return page === "jobs" ? <JobsView /> : page === "discovery" ? <DiscoveryView /> : page === "screening" ? <ScreeningView /> : page === "applications" ? <ApplicationsView /> : page === "interviews" ? <InterviewsView /> : page === "settings" ? <SettingsView /> : <HelpView />; }
