import { describe, expect, it, vi } from "vitest";
import { DiscoveryService } from "@/application/discovery/service";
import { createConfiguredDiscoveryAdapter } from "@/application/discovery/source-adapters";
import { generateDiscoveryQuery, normalizeAndRank, type DiscoverySourceRecord } from "@/application/discovery/types";

const source: DiscoverySourceRecord = { source: "persisted", externalId: "p-1", profileUrl: "https://example.test/p-1", fullName: "A", email: "a@example.test", skills: ["TypeScript"], experienceYears: 5, profileText: "Senior TypeScript engineer", raw: {} };
describe("Module 1 discovery", () => {
  it("generates deterministic query and ranked evidence", () => { const input = { jobId: "00000000-0000-0000-0000-000000000001", title: "Tech Lead", jobDescription: "TypeScript platform engineer", skills: ["TypeScript"], minimumYears: 3 }; expect(generateDiscoveryQuery(input)).toEqual(generateDiscoveryQuery(input)); expect(normalizeAndRank(generateDiscoveryQuery(input), [source])[0].normalizedProfile.evidence.length).toBeGreaterThan(0); });
  it("returns an explainable semantic similarity component", () => { const query = { text: '"typescript" OR "platform" OR "engineer"', terms: ["typescript", "platform", "engineer"], minimumYears: 3 }; const ranked = normalizeAndRank(query, [source])[0].normalizedProfile; expect(ranked.semanticSimilarity).toBeGreaterThan(0); expect(ranked.keywordScore).toBeGreaterThan(0); expect(ranked.score).toBeGreaterThan(0); });
  it("allows a short job description when title and skills still form a valid query", () => { const input = { jobId: "00000000-0000-0000-0000-000000000001", title: "React", jobDescription: "ทีม", skills: ["TypeScript"], minimumYears: 0 }; expect(generateDiscoveryQuery(input).terms).toEqual(expect.arrayContaining(["react", "typescript"])); });
  it("keeps approval idempotency at service boundary", async () => { const approveResult = { candidateId: "c", applicationId: "a" }; const repository = { saveRun: vi.fn().mockResolvedValue("r"), saveResults: vi.fn(), approveResult: vi.fn().mockResolvedValue(approveResult) }; const service = new DiscoveryService({ search: vi.fn().mockResolvedValue([source]) }, repository); await expect(service.approve("r", "p-1", "00000000-0000-0000-0000-000000000001", "u", "")).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); await expect(service.approve("r", "p-1", "00000000-0000-0000-0000-000000000001", "u", "key")).resolves.toEqual(approveResult); });
  it("persists source records before ranked results", async () => { const repository = { saveRun: vi.fn().mockResolvedValue("r"), saveSourceRecords: vi.fn(), saveResults: vi.fn(), approveResult: vi.fn() }; const service = new DiscoveryService({ search: vi.fn().mockResolvedValue([source]) }, repository); await service.search({ jobId: "00000000-0000-0000-0000-000000000001", title: "Tech Lead", jobDescription: "TypeScript platform engineer", skills: ["TypeScript"], minimumYears: 3 }, "u"); expect(repository.saveSourceRecords).toHaveBeenCalledWith([source]); expect(repository.saveResults).toHaveBeenCalled(); });
  it("fails explicitly when no external source is configured", async () => { const previousEndpoint = process.env.DISCOVERY_SOURCE_ENDPOINT; const previousKey = process.env.DISCOVERY_SOURCE_API_KEY; delete process.env.DISCOVERY_SOURCE_ENDPOINT; delete process.env.DISCOVERY_SOURCE_API_KEY; await expect(createConfiguredDiscoveryAdapter().search({ text: "x", terms: ["x"], minimumYears: 0 })).rejects.toThrow("ยังไม่ได้ตั้งค่าแหล่งข้อมูลภายนอก"); if (previousEndpoint === undefined) delete process.env.DISCOVERY_SOURCE_ENDPOINT; else process.env.DISCOVERY_SOURCE_ENDPOINT = previousEndpoint; if (previousKey === undefined) delete process.env.DISCOVERY_SOURCE_API_KEY; else process.env.DISCOVERY_SOURCE_API_KEY = previousKey; });
});
