import { describe, expect, it } from "vitest";
import { CandidateService, type CandidateRepository } from "@/application/candidate-service";
import { JobService, type JobRepository } from "@/application/job-service";
const candidateRepo = (existing: Awaited<ReturnType<CandidateRepository["findByEmail"]>> = null): CandidateRepository => ({ async findByEmail() { return existing; }, async insert(value) { return value; } });
const jobRepo = (current: Awaited<ReturnType<JobRepository["findById"]>> = null): JobRepository => ({ async findAll() { return current ? [current] : []; }, async findById() { return current; }, async insert(value) { return value; }, async update(_id, expected, patch, actor) { if (!current || current.version !== expected) return null; return { ...current, title: patch.title ?? current.title, description: patch.description ?? current.description, department: patch.department ?? current.department, status: patch.status ?? current.status, version: expected + 1, updatedBy: actor, updatedAt: patch.updatedAt ?? current.updatedAt }; } });
describe("job and candidate services", () => {
  it("creates and updates a job with optimistic locking", async () => { const created = await new JobService(jobRepo()).create({ title: "Tech", description: "Lead" }, "u", "j"); expect(created.status).toBe("draft"); const updated = await new JobService(jobRepo({ ...created })).update("j", { title: "Tech 2", description: "Lead" }, 1, "u2"); expect(updated.version).toBe(2); await expect(new JobService(jobRepo()).update("missing", { title: "x", description: "y" }, 1, "u")).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("lists persisted jobs through the service", async () => { const job = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 1, updatedBy: "u" }; await expect(new JobService(jobRepo(job)).list()).resolves.toEqual([job]); });
  it("rejects stale job update", async () => { const current = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 2, updatedBy: null }; await expect(new JobService(jobRepo(current)).update("j", current, 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("converts a job repository race into conflict", async () => { const current = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 1, updatedBy: null }; const raceRepo: JobRepository = { async findAll() { return [current]; }, async findById() { return current; }, async insert(value) { return value; }, async update() { return null; } }; await expect(new JobService(raceRepo).update("j", current, 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("creates referral candidate and rejects duplicate email", async () => { const created = await new CandidateService(candidateRepo()).create({ fullName: "N", source: "referral", referrerName: "Team", email: "n@example.com" }, "u", "c"); expect(created.createdBy).toBe("u"); await expect(new CandidateService(candidateRepo(created)).create({ fullName: "N", source: "manual", email: "n@example.com" }, "u", "c2")).rejects.toMatchObject({ code: "CONFLICT" }); });
});
