import { describe, expect, it } from "vitest";
import { CandidateCrudService, CandidateService, type CandidateApplicationLink, type CandidateCrudRepository, type CandidateRepository } from "@/application/candidate-service";
import { JobService, type JobRepository } from "@/application/job-service";
const candidateRepo = (existing: Awaited<ReturnType<CandidateRepository["findByEmail"]>> = null): CandidateRepository => ({ async findByEmail() { return existing; }, async insert(value) { return value; } });
const jobRepo = (current: Awaited<ReturnType<JobRepository["findById"]>> = null): JobRepository => ({ async findAll() { return current ? [current] : []; }, async findById() { return current; }, async insert(value) { return value; }, async update(_id, expected, patch, actor) { if (!current || current.version !== expected) return null; return { ...current, title: patch.title ?? current.title, description: patch.description ?? current.description, department: patch.department ?? current.department, status: patch.status ?? current.status, version: expected + 1, updatedBy: actor, updatedAt: patch.updatedAt ?? current.updatedAt }; } });
const crudCandidate = (overrides: Partial<Awaited<ReturnType<CandidateRepository["findByEmail"]>>> = {}): NonNullable<Awaited<ReturnType<CandidateRepository["findByEmail"]>>> => ({ id: "c", fullName: "Candidate", email: "candidate@example.com", phone: "0800000000", source: "manual", sourceDetail: "LinkedIn", createdBy: "u", version: 1, ...overrides });
const crudRepo = (current: NonNullable<Awaited<ReturnType<CandidateRepository["findByEmail"]>>> | null = crudCandidate(), updateResult?: CandidateApplicationLink | null, deleteResult?: NonNullable<Awaited<ReturnType<CandidateRepository["findByEmail"]>>> | null): CandidateCrudRepository & { calls: string[] } => ({ calls: [], async findByEmail() { return current; }, async insert(value) { return value; }, async createWithApplication(input, actorId, key, hash) { this.calls.push(`${actorId}:${key}:${hash}:${input.jobId}`); return updateResult !== undefined ? updateResult as CandidateApplicationLink : { candidateId: "c", applicationId: "a", applicationVersion: 1, candidate: crudCandidate({ createdBy: actorId }) }; }, async findById() { return current; }, async update(_id, _version, input, actorId, application) { this.calls.push(application ? "update-with-application" : "update"); return updateResult !== undefined ? updateResult : { candidateId: "c", applicationId: application?.id ?? "", applicationVersion: application?.expectedVersion ? application.expectedVersion + 1 : 0, candidate: crudCandidate({ ...(input as Record<string, unknown>), createdBy: actorId, version: 2 }) }; }, async softDelete() { this.calls.push("delete"); return deleteResult !== undefined ? deleteResult : current ? { ...current, version: current.version + 1 } : null; } });
describe("job and candidate services", () => {
  it("creates and updates a job with optimistic locking", async () => { const created = await new JobService(jobRepo()).create({ title: "Tech", description: "Lead" }, "u", "j"); expect(created.status).toBe("draft"); const updated = await new JobService(jobRepo({ ...created })).update("j", { title: "Tech 2", description: "Lead" }, 1, "u2"); expect(updated.version).toBe(2); await expect(new JobService(jobRepo()).update("missing", { title: "x", description: "y" }, 1, "u")).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("lists persisted jobs through the service", async () => { const job = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 1, updatedBy: "u" }; await expect(new JobService(jobRepo(job)).list()).resolves.toEqual([job]); });
  it("rejects stale job update", async () => { const current = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 2, updatedBy: null }; await expect(new JobService(jobRepo(current)).update("j", current, 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("converts a job repository race into conflict", async () => { const current = { id: "j", title: "Tech", description: "Lead", status: "draft" as const, version: 1, updatedBy: null }; const raceRepo: JobRepository = { async findAll() { return [current]; }, async findById() { return current; }, async insert(value) { return value; }, async update() { return null; } }; await expect(new JobService(raceRepo).update("j", current, 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("creates referral candidate and rejects duplicate email", async () => { const created = await new CandidateService(candidateRepo()).create({ fullName: "N", source: "referral", referrerName: "Team", email: "n@example.com" }, "u", "c"); expect(created.createdBy).toBe("u"); await expect(new CandidateService(candidateRepo(created)).create({ fullName: "N", source: "manual", email: "n@example.com" }, "u", "c2")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("creates a candidate and application through the repository boundary", async () => { const repository = crudRepo(); const result = await new CandidateCrudService(repository).createWithApplication({ fullName: "New Candidate", email: "new@example.com", source: "discovery", jobId: "00000000-0000-0000-0000-000000000010" }, "u", "key-1", "hash-1"); expect(result.applicationId).toBe("a"); expect(repository.calls[0]).toContain("key-1"); await expect(new CandidateCrudService(repository).createWithApplication({ fullName: "bad", source: "discovery", jobId: "not-a-uuid" }, "u", "key-2", "hash-2")).rejects.toThrow(); await expect(new CandidateCrudService(repository).createWithApplication({ fullName: "bad", source: "discovery", jobId: "00000000-0000-0000-0000-000000000010" }, "u", "   ", "hash-3")).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); });
  it("updates a candidate and linked application with optimistic locking", async () => { const repository = crudRepo(); const service = new CandidateCrudService(repository); const result = await service.update("c", { fullName: "Updated", source: "manual" }, 1, "u", { id: "a", expectedVersion: 1, appliedAt: "2026-08-22T00:00:00.000Z" }); expect(result.candidate.fullName).toBe("Updated"); expect(repository.calls).toContain("update-with-application"); await expect(service.update("c", { source: "referral" }, 1, "u")).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); await expect(service.update("c", {}, 2, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("rejects missing candidates and repository races for update/delete", async () => { const missing = new CandidateCrudService(crudRepo(null)); await expect(missing.update("c", {}, 1, "u")).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(missing.remove("c", 1, "u")).rejects.toMatchObject({ code: "NOT_FOUND" }); const race = new CandidateCrudService(crudRepo(crudCandidate(), null, null)); await expect(race.update("c", {}, 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); await expect(race.remove("c", 1, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("soft deletes a candidate when the version is current", async () => { const repository = crudRepo(); const service = new CandidateCrudService(repository); const result = await service.remove("c", 1, "u"); expect(result.version).toBe(2); expect(repository.calls).toContain("delete"); await expect(service.remove("c", 2, "u")).rejects.toMatchObject({ code: "CONFLICT" }); });
});
