import { z } from "zod";
export const discoveryInputSchema = z.object({ jobId: z.string().uuid(), jobDescription: z.string().trim().min(20).max(20000), title: z.string().trim().min(1).max(160), skills: z.array(z.string().trim().min(1).max(80)).max(30).default([]), minimumYears: z.number().int().min(0).max(60).default(0) });
export type DiscoveryInput = z.infer<typeof discoveryInputSchema>;
export type DiscoveryQuery = { text: string; terms: string[]; minimumYears: number };
export type DiscoverySourceRecord = { source: string; externalId: string; profileUrl: string; fullName: string; email?: string; phone?: string; role?: string; company?: string; skills: string[]; experienceYears?: number; profileText: string; raw: Record<string, unknown> };
export type RankedDiscoveryCandidate = DiscoverySourceRecord & { normalizedProfile: { role: string; company: string; skills: string[]; score: number; evidence: string[]; concerns: string[] } };
export type DiscoverySourceAdapter = { search(query: DiscoveryQuery): Promise<DiscoverySourceRecord[]> };
export const generateDiscoveryQuery = (input: DiscoveryInput): DiscoveryQuery => { const terms = [...new Set([input.title, ...input.skills, ...input.jobDescription.split(/[^\p{L}\p{N}+#.]+/u)].map((term) => term.trim().toLocaleLowerCase()).filter((term) => term.length >= 3))].slice(0, 40); return { text: terms.map((term) => `"${term}"`).join(" OR "), terms, minimumYears: input.minimumYears }; };
export const normalizeAndRank = (query: DiscoveryQuery, records: DiscoverySourceRecord[]): RankedDiscoveryCandidate[] => records.map((record) => { const text = [record.role, record.company, record.profileText, ...record.skills].filter(Boolean).join(" ").toLocaleLowerCase(); const matches = query.terms.filter((term) => text.includes(term)); const score = Math.min(100, Math.round((matches.length / Math.max(1, query.terms.length)) * 80) + (query.minimumYears === 0 || (record.experienceYears ?? 0) >= query.minimumYears ? 20 : 0)); return { ...record, normalizedProfile: { role: record.role ?? "ไม่ระบุ", company: record.company ?? "ไม่ระบุ", skills: [...new Set(record.skills)], score, evidence: matches.map((term) => `พบคำสำคัญ ${term} ในโปรไฟล์`), concerns: record.experienceYears === undefined ? ["ไม่พบข้อมูลประสบการณ์"] : [] } }; }).sort((a, b) => b.normalizedProfile.score - a.normalizedProfile.score);
